# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 534e2c07741dcb4cc78a1180a11ba62c5acecee89b89e1554e4000a37767e69684c19ad36c48256e67f5cdfe23f47fcecd692bb7f7f46d87604093db07e23c08

test:
  secret_key_base: afacf4602ea052734e083d916d8d7802f5d44f02d18674adb3590ff16bcc41c6e4d65b595a3da548eb26edaee428bf6593c6446c2af7d3187760b214cd6afdbd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
